name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-cli
    steps:
      - name: Run a one-line script
        run: az --version
