name: Test-GitHub-Actions-With-Container-Runner

on:
  push:
  workflow_dispatch:

jobs:

  test-azure-cli:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-cli
    steps:
      - run: az --version

  test-powershell-core:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/powershell
    steps:
      - run: $PSVersionTable
