name: Test-GitHub-Actions-With-Container-Runner

on:
  push:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-cli
    steps:
      - run: az --version
